apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:  # these labels are deployement labels
    app: mongodb
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:  # these labels are find pod lables 
      app: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      name: mongodb
      labels:  # these labels are pod  labels
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: brahmamdevops/mongodb:v1
        imagePullPolicy: Always



---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
